name: wf-ci-development
on:
  pull_request:
    branches:
      - develop
jobs:
  ci-developmemnt-job:
   runs-on: ubunbtu_latest
   steps:
     -name: Checkout Repository
      uses: actions/checkout@v4
     -name: Linthtml and css 
      run:  |
        npx htmlhint "**/*.html"
        npx styelelint "**/*.css"
     -name : Testbuuild Ops
      run:  |
        npx parcel build ".src/inde.html" --dist-dir "./dist" --public-url"./"
